version: '3'
services:
  mysql-container:
    image: mysql:8.0.30
    container_name: mysql-container-lab
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=lab_management
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456789
    networks:
      - lab-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web-container-lab:
    build:
      context: .
      dockerfile: dockerfile
    container_name: web-container-lab
    ports:
      - "8081:8080"
    networks:
      - lab-network

networks:
  lab-network:
    external: true