FROM openjdk:8-jdk-alpine

WORKDIR /app

# Sao chép file jar vào container
COPY target/demo-0.0.1-SNAPSHOT.jar app.jar

# Sao chép wait-for-it.sh vào container
COPY wait-for-it.sh /wait-for-it.sh

# Cấp quyền thực thi cho wait-for-it.sh
RUN chmod +x /wait-for-it.sh

# Sử dụng ENTRYPOINT để chạy wait-for-it.sh trước khi chạy ứng dụng Java
ENTRYPOINT ["./wait-for-it.sh", "mysql-container-lab:3306", "--", "java", "-jar", "app.jar"]
